version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    networks:
      - bridged
    expose:
      - "80"
      - "9000"
    volumes:
      - app_data:/var/www/html

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - "80"
    networks:
      - bridged
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  nginx:
    container_name: nginx-server
    image: lerenn/lets-encrypt-reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - bridged
    volumes:
      - app_data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - CERT1=poneytelecom.valentin-deville.eu
      - LETSENCRYPT_EMAIL=valentin@factorfx.com

networks:
  bridged:
    driver: 'bridge'

volumes:
  document_data:
  document_log:
  app_data:
